Features
ombralunare/memo pull request #13
Opened 2021-09-05 21:07 UTC by ombralunare

What I did so far ...

2021-09-07 03:03 UTC, CharlSteynberg requested changes

2021-09-07 04:13 UTC, ombralunare commented on index.html
> +        <link rel="audio" href="audio.mp"></link>
done

2021-09-07 07:49 UTC, ombralunare commented on script.js
> +var audioElement = new Audio(url);  // creates audio element for alarm //
please let me know how this is looking so far...
(haven't tested, waiting for ur approval/Review)

I haven't done the cards yet. Not too sure how to go about it. (is it similar to the code for "cardName"??) 
I haven't done any html yet - must i make the alarm button (loudButn) a 'submit' attr??

2021-09-07 08:35 UTC, CharlSteynberg reviewed
have you tested this?

2021-09-08 06:13 UTC, ombralunare commented
I've tested it and it doesn't work. It doesn't store the created card or provide a new one... 

Will get on it

2021-09-08 06:13 UTC, merged